# forgit,zoxide,starship installed via AUR

.tmux/plugins/tpm:
  type: archive
  url: https://github.com/tmux-plugins/tpm/archive/master.tar.gz
  stripComponents: 1

.local/grota/bash/30-completion-cheat.bash:
  type: file
  url: https://github.com/cheat/cheat/raw/master/scripts/cheat.bash

local/bin/diff-so-fancy:
  type: file
  url: https://github.com/so-fancy/diff-so-fancy/releases/download/v1.4.2/diff-so-fancy
  executable: true

.psysh/php_manual.sqlite:
  type: file
  url: http://psysh.org/manual/en/php_manual.sqlite

.local/grota/bash/30-exercism-autocomplete.bash:
  type: file
  url: https://raw.githubusercontent.com/exercism/cli/main/shell/exercism_completion.bash

local/bin/tmux-file-picker:
  type: file
  url: https://raw.githubusercontent.com/raine/tmux-file-picker/refs/heads/main/tmux-file-picker
  executable: true
