#!/usr/bin/env bash

# aliases {{{
alias tmxu=tmux
alias L='less -R'
alias df='df -h'
# https://github.com/Peltoche/lsd
alias ls='lsd'
alias ll='fzfllm'
alias l='lsd -l'
alias bc='bc -l'
alias py=python
alias nv=nordvpn
alias d=docker
alias dc=docker-compose
if [[ $(type -t compopt) = "builtin" ]]; then
    complete -o default -F __start_docker dc
else
    complete -o default -o nospace -F __start_docker dc
fi
alias ffmpeg='ffmpeg -hide_banner'
alias ffprobe='ffprobe -hide_banner'
function cc () {
  local CHROME=google-chrome
  if [ -n "$1" ]; then
    local PROFILE_DIR=$1
    local CHROME_ARGS="--user-data-dir=/home/grota/.config/${CHROME}_others/$PROFILE_DIR"
  fi
  echo "Running: " "$CHROME" "$CHROME_ARGS"
  $CHROME "$CHROME_ARGS" &> /dev/null &
}
alias pg='pgrep -a'
alias rstty='stty start undef stop undef'
alias ..="cd ../"
alias ..2="cd ../../"
alias ..3="cd ../../../"
alias ..4="cd ../../../../"
alias ..5="cd ../../../../../"
# there's a ss bin but that's ok for me
alias ss='sudo su -'
#alias xc='sleep 1.0; xdotool type "$(xclip -o -selection clipboard)"'
alias cat=bat
alias nvimo='NVIM_FLAVOUR=old nvim'
alias v=nvim
function rga() {
  rg --with-filename --line-number --column --smart-case --hidden -g='!.git/**' --no-ignore --no-ignore-parent --pretty "${@}" | LESS='' less --RAW-CONTROL-CHARS --ignore-case --quit-if-one-screen
}
#}}}

function slackupper() {
  while IFS= read -r -n1 char; do
    if [[ "$char" =~ [a-zA-Z] ]]; then
      echo -n ":alphabet-white-${char,,}:"
    elif [[ "$char" == ' ' ]]; then
      echo -n "  "
    elif [[ "$char" == '@' ]]; then
      echo -n ":alphabet-white-at:"
    elif [[ "$char" == '#' ]]; then
      echo -n ":alphabet-white-hash:"
    elif [[ "$char" == '?' ]]; then
      echo -n ":alphabet-white-question:"
    elif [[ "$char" == '!' ]]; then
      echo -n ":alphabet-white-exclamation:"
    else
      echo -n "$char"
    fi
  done
}
