#!/usr/bin/env bash

# functions {{{
function mkcd() { mkdir -p "$@" && eval cd "\"\$$#\""; }
function resunity() {
	xset r rate 200 90
	#synclient HorizTwoFingerScroll=1
	echo h xkb
	#setxkbmap -print | sed -e '/xkb_symbols/s/"[[:space:]]/+beppe_xkb_syms(beppe)&/' | xkbcomp -I${HOME}/.xkb - $DISPLAY >/dev/null  2>&1
}
# function whichpkg() { PACKAGE=$(dpkg -S "$(which "$1")" | cut -d':' -f1); echo "[${PACKAGE}]"; dpkg -s "${PACKAGE}" ;}
# }}}
