#!/usr/bin/env bash

# functions {{{
function mkcd() { mkdir -p "$@" && eval cd "\"\$$#\""; }
function resunity() {
	xset r rate 200 90
	echo h xkb
}
# }}}

bind -x '"\C-x\C-x": ~/.local/grota/scripts/tmux-action-dispatcher shortcuts-1'
