#!/usr/bin/env bash

export NNN_BMS='d:~/Downloads/;p:~/Dropbox/;c:~/Documents/encrypted_dropbox_data/burocrazia/banche'
export NNN_TRASH=1
export NNN_COLORS=7321
#auto-setup temporary NNN_FIFO
#indicates that the opener is a cli-only opener
export NNN_OPTS="acox"
export NNN_PLUG='c:fzz;p:preview-tui;i:imgview'
function n ()
{
    # Block nesting of nnn in subshells
    if [ -n "$NNNLVL" ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # NOTE: NNN_TMPFILE is fixed, should not be modified
    NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            \rm -f "$NNN_TMPFILE" > /dev/null
    fi
}
