#!/usr/bin/env bash

FORGIT_NO_ALIASES=1
alias "ga"='forgit::add'
alias "grs"='forgit::reset::head'
alias "gl"='forgit::log'
alias "gdi"='forgit::diff'
#alias "${forgit_ignore:-gi}"='forgit::ignore'
alias "gcof"='forgit::checkout::file'
alias "gcob"='forgit::checkout::branch'
#alias "${forgit_checkout_commit:-gco}"='forgit::checkout::commit'
alias "gclean"='forgit::clean'
alias "gstsh"='forgit::stash::show'
alias "gcp"='forgit::cherry::pick'
#alias "grbi"='forgit::rebase'
#alias "${forgit_fixup:-gfu}"='forgit::fixup'

alias "gll"='forgit::log --all'
