#!/usr/bin/env bash

function __starship_precmd_grota() {
  if [[ "${KUBE_PS1_ENABLED:-}" == "off" ]]; then
    unset GROTA_KUBE_STARSHIP
  else
    export GROTA_KUBE_STARSHIP=1
  fi
}
starship_precmd_user_func="__starship_precmd_grota"
eval "$(starship init bash)"
