# THIS IS EXPERIMENTAL
# the config file schema may change at any time

style:
  tag:
    color: green # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 5 # column width relative to the terminal window
    min_width: 15 # minimum column width as number of characters
  comment:
    color: white
    width_percentage: 30
    min_width: 25
  snippet:
    color: blue
    width_percentage: 60
    min_width: 45

finder:
  command: fzf # equivalent to the --finder option
  overrides: --tac --height 45
  overrides_var: --tac --height 32

# cheats:
  # paths:
    # - /path/to/some/dir
    # - /path/to/another/dir
  # path: /path/to/some/dir # (DEPRECATED) equivalent to the --path option

# search:
  # tags: git,!checkout # equivalent to the --tag-rules option

shell:
  command: bash # shell used for shell out. possible values: bash, zsh, dash, ...

