#!/usr/bin/env bash

GROUP="${1:-default}"
if [ "$GROUP" == "default" ]; then
  action="$(echo -e 'file\npaste_navi\nsession save\nsession restore\ntmux-fzf'| fzf --tmux)"
  if [ "$action" = "paste_navi" ]; then
    # Here we want to paste the navi snippet into the pane.
    # From https://github.com/denisidoro/navi/blob/master/docs/widgets/howto/TMUX.md
    # Added -s \"\" to avoid immediate execution
    tmux display-popup -w '90%' -h '90%' -EE "$SHELL --login -i -c 'navi --print | tmux load-buffer -b tmp - ; tmux paste-buffer -p -b tmp -d -s \"\" '"
  elif [ "$action" = "session restore" ]; then
    tmux display-popup -EE "navi --best-match --query 'tmux session restore'"
  elif [ "$action" = "session save" ]; then
    tmux display-popup -EE "navi --best-match --query 'tmux session save'"
  elif [ "$action" = "tmux-fzf" ]; then
    /home/grota/.tmux/plugins/tmux-fzf/main.sh
  elif [ "$action" = 'file' ]; then
    tmux display-popup -w 90% -h 90% -EE "tmux-file-picker"
  fi
elif [ "$GROUP" == "keybindings" ]; then
  action=$(tmux list-keys | awk '{ for (i=1; i<NF; i++) if ($i=="-T") { print $(i+1); break } }'|sort -u | fzf --tmux)
  tmux list-keys -T "$action" | fzf --tmux 98%,98% > /dev/null || exit 0
else
  echo "Invalid GROUP: $GROUP."
  exit 1
fi
