#!/usr/bin/env bash

FIRST="${1:-}"
SECOND="${2:-}"
if [ -z "$FIRST" ]; then
  FIRST="file-dir\nsession restore\ntmux-fzf\nsession save"
  if [ -n "$TMUX" ]; then
    FIRST="${FIRST}\nkeybindings\nSend key to all panes"
  fi
    FIRST="$(echo -e "$FIRST" | fzf --tmux)"
fi
# Map human labels to action names.
if [ "$FIRST" = "Send key to all panes" ]; then
  FIRST="send-keys-to-all-panes"
fi
if [ "$FIRST" == "keybindings" ]; then
  # Second arg is tmux table in this context.
  if [ -z "$SECOND" ]; then
    SECOND=$(tmux list-keys | awk '{ for (i=1; i<NF; i++) if ($i=="-T") { print $(i+1); break } }'|sort -u | fzf --tmux)
  fi
  tmux list-keys -T "$SECOND" | fzf --tmux 98%,98% > /dev/null || exit 0
elif [ "$FIRST" = "paste_navi" ]; then
  # Here we want to paste the navi snippet into the pane.
  # From https://github.com/denisidoro/navi/blob/master/docs/widgets/howto/TMUX.md
  # Added -s \"\" to avoid immediate execution
  tmux display-popup -w '90%' -h '90%' -EE "$SHELL --login -i -c 'navi --print | tmux load-buffer -b tmp - ; tmux paste-buffer -p -b tmp -d -s \"\" '"
elif [ "$FIRST" = "session restore" ]; then
  tmux display-popup -E "navi --best-match --query 'tmux session restore'" || true
elif [ "$FIRST" = "session save" ]; then
  tmux display-popup -E "navi --best-match --query 'tmux session save'" || true
elif [ "$FIRST" = "tmux-fzf" ]; then
  /home/grota/.local/share/tmux/plugins/tmux-fzf/main.sh
elif [ "$FIRST" = 'file-dir' ]; then
  if [ -z "$SECOND" ]; then
    SECOND=$(echo -e 'files\ndirs\nzoxide\nzoxide-and-files\nzoxide-and-dirs'| fzf --tmux)
    if [ "$SECOND" == 'files' ]; then
      TMUX_FILE_PICKER_ARGS=''
    elif [ "$SECOND" == 'dirs' ]; then
      TMUX_FILE_PICKER_ARGS='--directories'
    elif [ "$SECOND" == 'zoxide' ]; then
      TMUX_FILE_PICKER_ARGS='--zoxide --dir-only'
    elif [ "$SECOND" == 'zoxide-and-files' ]; then
      TMUX_FILE_PICKER_ARGS='--zoxide'
    elif [ "$SECOND" == 'zoxide-and-dirs' ]; then
      TMUX_FILE_PICKER_ARGS='--zoxide --directories'
    fi
  fi
  tmux display-popup -w 90% -h 90% -EE "tmux-file-picker $TMUX_FILE_PICKER_ARGS"
elif [ "$FIRST" = "send-keys-to-all-panes" ]; then
  # Second arg is the scope: "panes of the window" (default) or "panes of the session".
  if [ -z "$SECOND" ]; then
    SECOND=$(echo -e 'panes of the window\npanes of the session' | fzf --tmux) || exit 0
  fi
  if [ "$SECOND" = "panes of the session" ]; then
    SCOPE_FLAG="-s"
    TARGET="$(tmux display-message -p '#{session_id}')"
  else
    SCOPE_FLAG=""
    TARGET="$(tmux display-message -p '#{window_id}')"
  fi
  tmux display-popup -E -h 3 -w 60% "$0 send-keys-to-all-panes-prompt '$TARGET' $SCOPE_FLAG"
elif [ "$FIRST" = "send-keys-to-all-panes-prompt" ]; then
  # Internal: runs inside the popup. Second arg is the target window or session id,
  # third arg is the optional list-panes scope flag (-s for the whole session).
  read -r -e -p "Send keys to all panes: " KEYS || exit 0
  [ -z "$KEYS" ] && exit 0
  tmux list-panes ${3:-} -t "$SECOND" -F '#{pane_id}' | while read -r PANE; do
    tmux send-keys -t "$PANE" "$KEYS" Enter
  done
elif [ "$FIRST" = 'shortcuts-1' ]; then
  navi --tag-rules='trending-commands'
fi
