#!/bin/bash

# Just to be sure if you invoke it directly and not via git ctags (where pwd is already root of repo)
if [ ! -d .git ]; then
  echo Not in root dir of git repo, doing nothing. 1>&2
  exit 1
fi

trap "rm -f .git/tags.$$" EXIT

EXTRA_OPTION=''
if [ -f index.php ] && [ -d sites ] && [ -d modules ] && [ -d themes ]; then
  echo Found Drupal
  EXTRA_OPTION="--options=$DOTFILESREPO/ctags/drupal.ctags"
fi
# forced for the moment
EXTRA_OPTION="--options=$DOTFILESREPO/ctags/drupal.ctags"
FUGITIVE_COMPATIBLE_OPTION="--options=$DOTFILESREPO/ctags/relative_format.ctags"
ctags -Rf.git/tags.$$ $EXTRA_OPTION "$FUGITIVE_COMPATIBLE_OPTION"
mv .git/tags.$$ .git/tags
