#!/bin/bash

# Just to be sure if you invoke it directly and not via git ctags (where pwd is already root of repo)
if [ ! -d .git ]; then
  echo Not in root dir of git repo, doing nothing. 1>&2
  exit 1
fi

trap "rm -f .git/tags.$$" EXIT

EXTRA_EXCLUDE=''
if [ -f index.php ] && [ -d sites ] && [ -d modules ] && [ -d themes ]; then
  echo Found Drupal, excluding 'sites/*/files'
  EXTRA_EXCLUDE="--exclude=sites/*/files --exclude=cache --exclude=spark.phar --exclude=node_modules"
fi
ctags --tag-relative=yes -Rf.git/tags.$$ --exclude=.git --languages=-javascript,sql,C++,C,HTML,Ruby --kinds-PHP=-a $EXTRA_EXCLUDE
mv .git/tags.$$ .git/tags
