#!/bin/bash

set -e

if [ ! -d .git ]; then
  echo Not in root dir of git repo, doing nothing. 1>&2
  exit 1
fi

DEFAULT_PATH_TO_WEB=src/drupal/web
path_to_web=$1
if [ -z "$1" ]; then
  echo missing web dir of drupal defaulting to $DEFAULT_PATH_TO_WEB
  path_to_web=$DEFAULT_PATH_TO_WEB
fi
export path_to_web

rm -fr .phpactor_autoloader .phpactor.yml

cp -r "$DOTFILESREPO/chezmoi_ignored/phpactor/" .phpactor_autoloader
envsubst '$path_to_web' < "$DOTFILESREPO/chezmoi_ignored/phpactor/composer.json" > .phpactor_autoloader/composer.json
mv .phpactor_autoloader/dot_phpactor.yml .phpactor.yml
grep -qF /.phpactor.yml .git/info/exclude && echo local git exclude already has /.phpactor.yml || echo /.phpactor.yml >> .git/info/exclude
grep -qF /.phpactor_autoloader .git/info/exclude && echo local git exclude already has /.phpactor_autoloader || echo /.phpactor_autoloader >> .git/info/exclude
composer --working-dir=.phpactor_autoloader up --lock
echo "all done"
