# https://yazi-rs.github.io/docs/tips/#dropping-to-shell
[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

# --- https://github.com/dedukun/bookmarks.yazi
[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

# --- override to https://github.com/sxyazi/yazi/blob/v26.1.22/yazi-config/preset/keymap-default.toml
# https://yazi-rs.github.io/docs/tips/#confirm-quit
[[mgr.prepend_keymap]]
on  = "q"
run = "plugin confirm-quit no-cwd-file"
desc = "Quit without changing dir"

[[mgr.prepend_keymap]]
on = "Q"
run = 'noop'

[[mgr.prepend_keymap]]
on  = ["<C-x>", '<C-x>']
run = "plugin confirm-quit"
desc = "Quit changin dir"

[[mgr.prepend_keymap]]
on  = "<C-c>"
run = "close --no-cwd-file"
desc = "Close tab (exit without changing dir)"

[[mgr.prepend_keymap]]
on  = "<Tab>"
run = "tab_create --current"
desc = "Create new Tab on CWD"

[[mgr.prepend_keymap]]
on  = ["<C-x>", "s"]
run = "spot"
desc = "Spot/stat hovered file"

[[help.prepend_keymap]]
on = ['/']
run = 'filter'
desc = 'filter help items'
