# https://yazi-rs.github.io/docs/tips/#dropping-to-shell
[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

# --- https://github.com/dedukun/bookmarks.yazi
[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

# --- override to https://github.com/sxyazi/yazi/blob/v26.1.22/yazi-config/preset/keymap-default.toml
# https://yazi-rs.github.io/docs/tips/#confirm-quit
[[mgr.prepend_keymap]]
on  = "<C-c>"
run = "close --no-cwd-file"
desc = "Close tab (No change CWD)"

[[mgr.prepend_keymap]]
on  = "q"
run = "close --no-cwd-file"
desc = "Close tab (No change CWD)"

[[mgr.prepend_keymap]]
on = "Q"
run = "plugin confirm-quit no-cwd-file"
desc = "Quit ALL, NO change CWD"

[[mgr.prepend_keymap]]
on  = ["<C-x>", 'q']
run = "plugin confirm-quit"
desc = "Quit ALL, change CWD"

[[mgr.prepend_keymap]]
on  = ["<C-x>", 'n']
run = "tab_create --current"
desc = "New tab"

[[mgr.prepend_keymap]]
on  = "<Tab>"
run = "tab_switch 1 --relative"
desc = "Next tab"

[[mgr.prepend_keymap]]
on  = "<S-Tab>"
run = "tab_switch -1 --relative"
desc = "Previous tab"

[[mgr.prepend_keymap]]
on  = ["<C-x>", "s"]
run = "spot"
desc = "Spot/stat hovered file"

[[help.prepend_keymap]]
on = ['/']
run = 'filter'
desc = 'filter help items'
