#!/bin/bash

# Just to be sure if you invoke it directly and not via git ctags (where pwd is already root of repo)
if [ ! -d .git ]; then
  echo Not in root dir of git repo, doing nothing. 1>&2
  exit 1
fi

trap "rm -f .git/tags.$$" EXIT


EXTRA_OPTION=""
if [ "$1" == drupal ]; then
  EXTRA_OPTION="--options=$DOTFILESREPO/chezmoi_ignored/ctags/drupal.ctags"
  shift
fi

if [ -f .git/hooks/ctags_local_options ]; then
  echo Adding local exclude
  cat .git/hooks/ctags_local_options
  EXTRA_OPTION="$EXTRA_OPTION --options=.git/hooks/ctags_local_options"
fi
FUGITIVE_COMPATIBLE_OPTION="--options=$DOTFILESREPO/chezmoi_ignored/ctags/relative_format.ctags"
echo calling ctags with $EXTRA_OPTION "$FUGITIVE_COMPATIBLE_OPTION" "$@"
ctags -Rf.git/tags.$$ $EXTRA_OPTION "$FUGITIVE_COMPATIBLE_OPTION" "$@"
mv .git/tags.$$ .git/tags
