#!/usr/bin/env bash
# vim: set tabstop=2 shiftwidth=2 foldmethod=marker:

current_pathinrepo=$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )

# Make Bash append rather than overwrite the history on disk
shopt -s histappend

# as per instructions in the script, let's not call ps1_set, but call
# ps1_update inside PROMPT_COMMAND.
if [[ "$PROMPT_COMMAND" != *"ps1_update"* ]]; then
  export PROMPT_COMMAND="history -a; history -n; ps1_update --notime --prompt \>"
fi
[[ -s "${current_pathinrepo}/ps1_functions" ]] && source "${current_pathinrepo}/ps1_functions"
KUBE_PS1_NS_COLOR=green
KUBE_PS1_CTX_COLOR=yellow
[[ -s "${current_pathinrepo}/kube-ps1.sh" ]] && source "${current_pathinrepo}/kube-ps1.sh"

if [[ ! ( "$PATH" == *"$HOME/local/bin:$HOME/.config/composer/vendor/bin"* ) ]]; then
  export PATH=$HOME/local/bin:$HOME/.config/composer/vendor/bin:$PATH
fi
export PATH="$(go env GOPATH)/bin:$HOME/.local/bin/:$PATH"

#_Z_CMD=j . "${DOTFILESREPO}"/bin/rupa_z/z.sh
. "${DOTFILESREPO}"/bin/rupa_z/z.sh

export EDITOR=nvim
export MANPAGER="sh -c 'col -bx | bat --language=man -p'"
HISTFILESIZE=1000000
HISTSIZE=500000
HISTCONTROL="erasedups:ignoreboth"
HISTIGNORE="clear:bg:fg:cd:cd -:exit:date:w:gs:gss:ga:gau:gk:gd:gdc:gf:gb:grbi:gcm*:l:resunity:ss:"

# disable <CTRL-S> and <CTRL-Q> terminal settings, I want to use them in vim
# maybe there's a better way, see :h term.txt in vim
stty stop undef
stty start undef

[ -n "$PS1" ] && (export BINPATHS=(${PATH//:/ }) && whatis "$(find "${BINPATHS[@]}" -maxdepth 1 -printf '%f\n' -type f 2>/dev/null| shuf -n 1)")

# Less Colors for Man Pages
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline
export LESS="-iRS"

# load my private stuff
[[ -s "${DOTFILESREPO}/private/bash/_bash_aliases" ]] && source "${DOTFILESREPO}/private/bash/_bash_aliases"

# oh god, this feels good
[[ -n "$DISPLAY" ]] && xset r rate 200 90

# scm_breeze {{{
source "${current_pathinrepo}/scm_breeze/scm_breeze.sh"
# }}}

function whichpkg() { PACKAGE=$(dpkg -S "$(which "$1")" | cut -d':' -f1); echo "[${PACKAGE}]"; dpkg -s "${PACKAGE}" ;}

source "${DOTFILESREPO}/bin/the_silver_searcher/ag.bashcomp.sh"

# Cannot use a ~/.bash_completion (that ~/.bashrc would source)
# because this needs to happen after our actions.
for f in "$DOTFILESREPO"/bash/completions/*; do
  source "$f"
done
complete -C "$HOME"/local/bin/aws_completer aws
export NNN_BMS='d:~/Downloads/;p:~/Dropbox/;c:~/Documents/encrypted_dropbox_data/burocrazia/banche'
export NNN_TRASH=1
export NNN_COLORS=7321
#auto-setup temporary NNN_FIFO
#indicates that the opener is a cli-only opener
export NNN_OPTS="acox"
export NNN_PLUG='c:fzz;p:preview-tui;i:imgview'
function n ()
{
    # Block nesting of nnn in subshells
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # NOTE: NNN_TMPFILE is fixed, should not be modified
    NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            \rm -f "$NNN_TMPFILE" > /dev/null
    fi
}

export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_BUILDKIT=1
#export LD_LIBRARY_PATH=/usr/local/lib
