#!/usr/bin/env bash
# vim: set tabstop=2 shiftwidth=2 foldmethod=marker:

# ~/.profile or ~/.bash_profile read only by interactive shells
# ~/.profile is not read if ~/.bash_profile or ~/.bash_login exists.
# look into the dropbox-only phpenv_phpbuild branch for a sane .bash_profile

# source an extra file for non aliases/function stuff
if [ -f ~/.bash_extras ]; then
    . ~/.bash_extras
fi
# source drush aliases and completion
if [ -f ~/.drush_bashrc  ]; then
    . ~/.drush_bashrc
fi

# aliases {{{
alias L='less -R'
alias df='df -h'
alias ll='ls -AlFh'
alias sl=ls
alias fire='firefox -Profilemanager -no-remote &> /dev/null &'
function cc () {
  if [ -z "$1" ]; then
    echo "Error: Argument missing. Specify a chrome session id"
    return 1;
  fi
  dirname=$1
  google-chrome --user-data-dir=/home/grota/.config/google-chrome_others/$dirname &> /dev/null &
}
alias pg='pgrep -l'
alias pw='pwsafe -Eup -l'
alias pwc='pwsafe -px'
alias rstty='stty start undef stop undef'
alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."
alias ..5="cd ../../../../.."
alias cd..="cd ../"
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias cd.....="cd ../../../.."
alias cd......="cd ../../../../.."
alias bc='bc -l'
alias grep='grep -n --exclude-dir=.svn --exclude-dir=.git '
# there's a ss bin but that's ok for me
alias ss='sudo su -'
# {tl,ll,rl}php log {{{
alias tlphp='tail -F /tmp/php5_apache_errorlog.log'
alias llphp='less /tmp/php5_apache_errorlog.log'
alias rlphp='sudo rm /tmp/php5_apache_errorlog.log'
#}}}
#alias rmine='RUBYMINE_JDK=~/Downloads/jdk1.6.0_30 mine &> /dev/null &'
#alias storm='WEBIDE_JDK=~/Downloads/jdk1.6.0_30 pstorm &> /dev/null &'
# Acer specific {{{
alias toff='xinput set-prop "SynPS/2 Synaptics TouchPad" 140 0'
alias ton='xinput set-prop "SynPS/2 Synaptics TouchPad" 140 1'
alias koff='xinput set-prop "AT Translated Set 2 keyboard" 140 0'
alias kon='xinput set-prop "AT Translated Set 2 keyboard" 140 1'
#}}}
alias unmute='amixer set Speaker,0 unmute &> /dev/null ; amixer set Speaker,0 100% &> /dev/null'

# vim aliases {{{
# alias for v, vim wrapper at https://github.com/rupa/v.git
# aka: v list standalone
alias vls='v -l'
# aka: v list, reuse vim server session
alias vl='vim="eval $(type vim  | tail -n +2); vim" v -l'
# aka: vim standalone
alias vs="stty start undef stop undef && exec_scmb_expand_args $(which 2>/dev/null vim)"
# vim function that shadows aliases and commands
function vims {
  vim_orig=$(which 2>/dev/null vim)
  $vim_orig --serverlist | grep -q TROLOLOL
  # if server is running
  if [ $? -eq 0 ]; then
      $vim_orig --servername TROLOLOL --remote-silent "$@"
  else
      $vim_orig "$@" --servername TROLOLOL
  fi
}
# alias vi to vim (this is to keep using the vim() bash function that uses the vim --remote feature)
alias vi="stty start undef stop undef && exec_scmb_expand_args vims"
alias vim="stty start undef stop undef && exec_scmb_expand_args vims"
#}}}

#git aliases {{{
alias gg='git grep --break --heading --line-number'
alias gbv='git branch -avv'
alias gbf='git branch -f'
alias gau='git add -u'
alias gdcw='git diff --cached --word-diff --'
alias gl='git --no-pager l -n12'
alias k='git --no-pager ll -n12'
alias gk='gitk --all&'
alias gst='git stash'
alias gstp='git stash pop --index'
alias gl1p="git log -1 -p"
# from scm_breeze
alias gsubrm="git_submodule_rm"
# c --rebuild to rebuild the cache
function _git_abbrev_hash_complete () {
  local curw
  local MAX_REVS
  MAX_REVS=10
  COMPREPLY=()
  if [[ $COMP_CWORD == 2 ]]; then
    return
  fi
  IFS=$'\n'
  curw=${COMP_WORDS[COMP_CWORD]}
  #display a reminder
  if [[ $COMP_TYPE == 9 && $curw == '' ]]; then
    echo
    git --no-pager log --oneline -n${MAX_REVS}
  fi
  COMPREPLY=($(compgen -W '$(git log --pretty=format:%h -n'$MAX_REVS')' -- $curw))
  IFS=$' \t\n'
}
complete -F _git_abbrev_hash_complete gsf
complete -F _git_abbrev_hash_complete gl1p
# from scm_breeze
__define_git_completion gbf branch
complete -o default -o nospace -F _git_gbf_shortcut gbf
#}}}


# old stuff, still used {{{
alias STO='sudo mdadm -S /dev/md0'
alias STA='sudo mdadm -As /dev/md0'
#alias vci='vi config.inc.php'
#alias c='cat /proc/mdstat'
#alias rs='rsync -av --delete'
#alias k='kompare -no -'
#alias svnd='svn diff --diff-cmd diff | colordiff | less -r'
#xmessage -nearmouse "Some important message"
#}}}
#}}}

# functions {{{
function rec() {
  if [ -z "$1" ]; then
    echo 'provide an output file'
    return
  fi
  count=4
  while [ $count -gt 0  ]; do
    echo $count ...
    count=$(( $count - 1  ))
    sleep 1
  done
  gst-launch-1.0 -e pulsesrc device="alsa_output.pci-0000_00_1b.0.analog-surround-40.monitor" ! audioconvert ! lamemp3enc target=1 bitrate=128 cbr=true ! filesink location=${1}.mp3
}
function mkcd() { mkdir -p "$@" && eval cd "\"\$$#\""; }
#}}}
