#!env bash
# vim: set tabstop=2 shiftwidth=2 foldmethod=marker:

# source and extra file for non aliases/function stuff
if [ -f ~/.bash_extras ]; then
    . ~/.bash_extras
fi

# aliases {{{
alias L='less -R'
alias df='df -h'
alias ll='ls -AlFh'
alias sl=ls
alias fire='firefox -Profilemanager -no-remote &'
alias pg='ps aux| grep '
alias pw='pwsafe -Eup -l'
alias pwc='pwsafe -px'
alias rstty='stty start undef stop undef'
alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."
alias ..5="cd ../../../../.."
alias cd..="cd ../"
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias cd.....="cd ../../../.."
alias cd......="cd ../../../../.."
alias bc='bc -l'
alias grep='grep -n --exclude-dir=.svn --exclude-dir=.git '
alias pb='vi ~/.config/pianobar/config'
# {tl,ll,rl}php log {{{
alias tlphp='tail -F /tmp/php5_apache_errorlog.log'
alias llphp='less /tmp/php5_apache_errorlog.log'
alias rlphp='sudo rm /tmp/php5_apache_errorlog.log'
#}}}
alias jl='jumpstat'

# Acer specific {{{
alias toff='xinput set-prop "SynPS/2 Synaptics TouchPad" 132 0'
alias koff='xinput set-prop "AT Translated Set 2 keyboard" 132 0'
#}}}

# vim aliases {{{
# alias for v, vim wrapper at https://github.com/rupa/v.git
# aka: v list standalone
alias vls='v -l'
# aka: v list, reuse vim server session
alias vl='vim="eval $(type vim  | tail -n +2); vim" v -l'
alias vs="exec_git_expand_args $(which 2>/dev/null vim)"
# vim function that shadows aliases and commands
function vim {
  vim_orig=$(which 2>/dev/null vim)
  $vim_orig --serverlist | grep -q TROLOLOL
  # if server is running
  if [ $? -eq 0 ]; then
      $vim_orig --servername TROLOLOL --remote-silent "$@"
  else
      $vim_orig "$@" --servername TROLOLOL
  fi
}
# alias vi to vim (this is to keep using the vim() bash function that uses the vim --remote feature)
alias vi="exec_git_expand_args vim"
#}}}

#git aliases {{{
alias gb='git branch -vv'
alias gdw='exec_git_expand_args git diff --word-diff --'
alias gdcw='exec_git_expand_args git diff --cached --word-diff --'
alias gl='git --no-pager l -n12'
alias k='git --no-pager ll -n12'
alias gk='gitk --all&'
# from scm_breeze
alias gsubrm="git_submodule_rm"
#}}}


# old stuff, still used {{{
alias STO='sudo mdadm -S /dev/md0'
alias STA='sudo mdadm -As /dev/md0'
alias vci='vi config.inc.php'
#alias c='cat /proc/mdstat'
#alias rs='rsync -av --delete'
#alias k='kompare -no -'
#alias svnd='svn diff --diff-cmd diff'
#}}}
#}}}

# functions {{{
function pianobar {
  # only way I found, short of unsetting PS1.
  # due to variable visibility, methinks
  echo -ne "\033]0;pianobar\a"
  command pianobar
}
function mkcd () { mkdir -p "$@" && eval cd "\"\$$#\""; }

# as in bash-title
function bt {
  export GROTA_TITLE="$*"
}
#}}}
