#!/usr/bin/env bash
# vim: set tabstop=2 shiftwidth=2 foldmethod=marker:

#git aliases {{{
alias gg='git grep --break --heading --line-number'
alias gbv='git branch -avv'
alias gbf='git branch -f'
alias gau='git add -u :/'
alias gaud='git add -u .'
alias gl='git --no-pager l -n12'
__git_alias "gf" "git" "fetch" "-p"
alias k='git --no-pager ll -n12'
alias gk='gitk --all&'
alias gl1p="git log -1 -p"
__git_alias "gdw" "git" "diff" "-w --"
__git_alias "gdcw" "git" "diff" "--cached -w --"
__git_alias "gdcwd" "git" "diff" "--word-diff --cached --"
__git_alias "gst" "git" "stash" "list"
__git_alias "gsts" "git" "stash" "save"
__git_alias "gcmh" "git" "commit" "--amend -C HEAD"
alias gstsh='git stash show -p'
alias gsta='git stash apply'
alias gstd='git stash drop'
alias gstp='git stash pop --index'
__git_complete gstsh _git_gstsh
__git_complete gsta _git_gstsh
__git_complete gstd _git_gstsh
__git_complete gstp _git_gstsh
function _git_gstsh () {
  cword=2
  words[1]=show
  _git_stash
}
# from scm_breeze
alias gsubrm="git_submodule_rm"
function _git_abbrev_hash_complete () {
  local curw MAX_REVS
  MAX_REVS=10
  COMPREPLY=()
  if [[ $COMP_CWORD == 2 ]]; then
    return
  fi
  IFS=$'\n'
  curw=${COMP_WORDS[COMP_CWORD]}
  # display a reminder, on first tab press
  if [[ $COMP_CWORD == 1 && $curw == '' ]]; then
    git --no-pager log --oneline -n${MAX_REVS}
  fi
  COMPREPLY=($(compgen -W '$(git log --pretty=format:%h -n'$MAX_REVS')' -- $curw))
  IFS=$' \t\n'
}
complete -F _git_abbrev_hash_complete gsf
complete -F _git_abbrev_hash_complete gl1p
# from scm_breeze
__define_git_completion gbf branch
complete -o default -o nospace -F _git_gbf_shortcut gbf
#}}}
