#!/usr/bin/env bash
# vim: set tabstop=2 shiftwidth=2 foldmethod=marker:

#git aliases {{{
alias gg='git grep --break --heading --line-number'
alias gbv='git branch -avv'
alias gbf='git branch -f'
alias gau='git add -u'
alias gl='git --no-pager l -n12'
alias k='git --no-pager ll -n12'
alias gk='gitk --all&'
alias gl1p="git log -1 -p"
__git_alias "gdw" "git" "diff" "-w --"
__git_alias "gdcw" "git" "diff" "--cached -w --"
__git_alias "gdcwd" "git" "diff" "--word-diff --cached --"
# current autocomplete for stash is broken
__git_alias "gst" "git" "stash" "list"
__git_alias "gsts" "git" "stash" "save"
__git_alias "gsta" "git" "stash" "apply"
__git_alias "gstp" "git" "stash" "pop --index"
__git_alias "gstd" "git" "stash" "drop"
__git_alias "gstsh" "git" "stash" "show -p"
# from scm_breeze
alias gsubrm="git_submodule_rm"
function _git_abbrev_hash_complete () {
  local curw MAX_REVS
  MAX_REVS=10
  COMPREPLY=()
  if [[ $COMP_CWORD == 2 ]]; then
    return
  fi
  IFS=$'\n'
  curw=${COMP_WORDS[COMP_CWORD]}
  # display a reminder, on first tab press (9 is the ascii value of TAB, see man bash, COMP_TYPE)
  if [[ $COMP_TYPE == 9 && $curw == '' ]]; then
    echo
    git --no-pager log --oneline -n${MAX_REVS}
  fi
  COMPREPLY=($(compgen -W '$(git log --pretty=format:%h -n'$MAX_REVS')' -- $curw))
  IFS=$' \t\n'
}
complete -F _git_abbrev_hash_complete gsf
complete -F _git_abbrev_hash_complete gl1p
# from scm_breeze
__define_git_completion gbf branch
complete -o default -o nospace -F _git_gbf_shortcut gbf
#}}}
