#!/usr/bin/env bash
# vim: set tabstop=2 shiftwidth=2 foldmethod=marker:

# vim {{{
# aka: vim standalone
alias vs="stty start undef stop undef && exec_scmb_expand_args $(which 2>/dev/null vim)"
# _vimserver function to create/reuse vim server process
function _vimserver {
  command vim --serverlist | grep -q TROLOLOL
  if [ $? -eq 0 ]; then
      command vim --servername TROLOLOL --remote-tab-silent "$@"
  else
      command vim --servername TROLOLOL "$@"
  fi
}
alias vi="stty start undef stop undef && exec_scmb_expand_args _vimserver"
alias vim="stty start undef stop undef && exec_scmb_expand_args _vimserver"

# alias for v, vim wrapper at https://github.com/rupa/v.git
# aka: v list standalone
alias vls='v -l'
# aka: v list, reuse vim server session
alias vl='vim="eval $(type _vimserver | tail -n +2); _vimserver" v -l'
#}}}
