#!/usr/bin/env bash
# vim: set tabstop=2 shiftwidth=2 foldmethod=marker:

# vim {{{
# aka: vim standalone
alias vs="stty start undef stop undef && exec_scmb_expand_args $(which 2>/dev/null vim)"
# vims function to create/reuse vim server process
function vims {
  vim_orig=$(which 2>/dev/null vim)
  $vim_orig --serverlist | grep -q TROLOLOL
  # if server is running
  if [ $? -eq 0 ]; then
      $vim_orig --servername TROLOLOL --remote-silent "$@"
  else
      $vim_orig "$@" --servername TROLOLOL
  fi
}
alias vi="stty start undef stop undef && exec_scmb_expand_args vims"
alias vim="stty start undef stop undef && exec_scmb_expand_args vims"

# alias for v, vim wrapper at https://github.com/rupa/v.git
# aka: v list standalone
alias vls='v -l'
# aka: v list, reuse vim server session
alias vl='vim="eval $(type vims | tail -n +2); vims" v -l'
#}}}
